version: '3'

services:
  php:
    build:
      context: ./php
    volumes:
      - /Users/ruthnewman/documents/side-projects/pdo-contact-form/www:/var/www/app/public/
    working_dir: /var/www/app
  apache:
    build:
      context: ./apache
    volumes:
      - /Users/ruthnewman/documents/side-projects/pdo-contact-form/www:/var/www/app/public/
    ports:
      - 8282:80
    links:
      - php
